#!/usr/bin/env bash
set -Eeuo pipefail

current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)

if [ "$current_branch" != "main" ]; then
    # We are not on main, so skip checks
    exit 0
fi

cargo fmt -- --check
cargo machete --with-metadata
cargo clippy --all-targets -- -D warnings
